language: rust
rust:
  - nightly
  - stable
  - 1.12.0
  - 1.8.0

os:
  - linux
  - osx

script:
  - rustc --version | grep nightly && cargo test --features=simd || ( echo skip && rustc --version | grep -v nightly )
  - cargo test
  - cargo test --features=no-stdlib
  - cargo test --release
  - rustc --version | grep 1[.][89][.] || rustc --version | grep -v 1[.]2[789][.]0 | grep 1[.][12][0-9][.]||cargo build --features=validation

matrix:
  exclude:
    - rust: 1.8.0
      os: osx
