language: rust
rust:
  - nightly
  - stable
  - 1.12.0
  - 1.8.0

os:
  - linux
  - osx

script:
  - rustc --version | grep nightly && cargo test --features=simd || echo skip
  - cargo test
  - cargo test --features=no-stdlib
  - cargo test --release

matrix:
  exclude:
    - rust: 1.8.0
      os: osx
